vedit
dangilman/pyHalo pull request #10
Opened 2021-07-03 00:26 UTC by vdike

Added PBH realization functionality to realization_extensions class

2021-07-05 20:08 UTC, dangilman requested changes
thanks for pushing this! 

Most of my comments have to do with reorganizing the structure. If a function doesn't strictly have anything to do with an instance of Realization, it should be in utilities.py. Also, the function should be as general as possible, i.e. if it just generates points in a circle "pbh" should be left out of the function name (this makes the code a bit more readable, in my opinion).

Two other things: 1) eventually you'll need to write test functions for each routine, so think about how you can break the task down further into smaller bits that are each easy to test.
2) Add documentation to each function following the style in pyHalo (see for example find_core_collapsed_halos). PyCharm generates the documentation structure for you automatically, maybe Spider can do the same

2021-07-05 20:08 UTC, dangilman commented on pyHalo/realization_extensions.py
> +                coord_x_smooth, coord_y_smooth,  z_shifts_smooth, masses_smooth = self._smooth_pbh (max_rendering_range, Nsmooth, center_x, center_y, zi, M)
regarding the comments above, this line should return the coord_x/y_smooth arrays, and the z_shifts_smooth can be defined in the line immediately following. For now, you can just create a list of masses, but if the future we might want to sample from a mass function (which is why you don't want to put that functionality where the halo coordinates are generated)

2021-07-05 20:08 UTC, dangilman commented on pyHalo/realization_extensions.py
> +                coord_x_clumpy, coord_y_clumpy, z_shifts_clumpy, masses_clumpy = self._clumpy_pbh (lens_model_list_at_plane, center_x, center_y,
same comment as above regarding the line following if Nsmooth > 0

2021-07-05 20:08 UTC, dangilman commented on pyHalo/realization_extensions.py
> +        max_rendering_range_base = 0.25 # arcsec
this should be an argument passed into the function

2021-07-05 20:08 UTC, dangilman commented on pyHalo/realization_extensions.py
> +        npix = 300
should be able to pass this into function also

2021-07-05 20:08 UTC, dangilman commented on pyHalo/realization_extensions.py
> +        mlow = 1e6
there are keyword arguments stored in the realization instance (self._realization) that define the mass range, access them with profile_args = self._realization._prof_params and then mlow = 10**profile_args['log_mlow'], etc.

2021-07-05 20:08 UTC, dangilman commented on pyHalo/realization_extensions.py
> +        profile_args = self._realization._prof_params
see above

2021-07-19 23:05 UTC, vdike commented on pyHalo/realization_extensions.py
> +    def _smooth_pbh(self, max_rendering_range, Nsmooth, center_x, center_y, zi, M):
I don't understand why I don't need to pass M and zi into the function when those are variables used in the function. Will it just pick those out of the namespace where they are defined?

2021-07-19 23:09 UTC, vdike commented on pyHalo/realization_extensions.py
> +    def _smooth_pbh(self, max_rendering_range, Nsmooth, center_x, center_y, zi, M):
Sorry, I see what you mean: that part can be removed from the fn entirely

2021-08-25 00:11 UTC, vdike commented
I added another commit with the improvements requested.

2021-09-08 00:19 UTC, closed without merging